#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocationService.Resource", IsApplication=true)]

namespace LocationService
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.TextToSpeech.Resource.String.ApplicationName = global::LocationService.Resource.String.ApplicationName;
			global::Plugin.TextToSpeech.Resource.String.Hello = global::LocationService.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int buttonOK = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int cancel = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int editPass = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int editPass2 = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int editUser = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int setUsername = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int space1 = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int space2 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int startService = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int stopService = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int textError = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int textPass = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textPass2 = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int textUser = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int user = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Alarm = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int beep_mp3 = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int set_new_user = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int set_user = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int start_service = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int stop_service = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
